# Generated by Django 4.2 on 2023-04-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company_url', models.CharField(blank=True, max_length=200, null=True)),
                ('tracker_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, help_text='company logo', null=True, upload_to=utils.path_and_rename)),
                ('manage_fulfillment', models.BooleanField(default=True, help_text='DIY managed your own fulfillment')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'In Active')], null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2fulfillment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
