# Generated by Django 2.2.17 on 2021-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
