# Generated by Django 2.2.17 on 2021-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210616_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
