# Generated by Django 2.2.17 on 2021-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], null=True),
        ),
        migrations.AlterField(
            model_name='productparent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active')], null=True),
        ),
    ]
