# Generated by Django 4.2 on 2023-04-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='package_height',
            field=models.FloatField(blank=True, help_text='package height', null=True),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='package_length',
            field=models.FloatField(blank=True, help_text='package weight', null=True),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='package_width',
            field=models.FloatField(blank=True, help_text='package width', null=True),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='weight',
            field=models.FloatField(blank=True, help_text='product  weight', null=True),
        ),
    ]
