# Generated by Django 4.2 on 2023-05-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantitem',
            name='package_height',
        ),
        migrations.RemoveField(
            model_name='variantitem',
            name='package_length',
        ),
        migrations.RemoveField(
            model_name='variantitem',
            name='package_width',
        ),
        migrations.RemoveField(
            model_name='variantitem',
            name='weight',
        ),
    ]
