# Generated by Django 2.2.17 on 2021-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210612_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
