# Generated by Django 2.2.17 on 2021-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productvariant_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='cover_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productparent',
            name='goods_brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
