# Generated by Django 2.2.17 on 2021-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210612_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
