# Generated by Django 2.2.17 on 2021-06-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productvariant_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
