# Generated by Django 2.2.17 on 2021-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210613_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
