# Generated by Django 3.2.4 on 2021-07-10 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_auto_20210624_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img_upload',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productparent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], null=True),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2tag', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant2tag', to='product.productvariant')),
            ],
        ),
    ]
