# Generated by Django 3.2.4 on 2021-07-10 04:38

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210710_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='img_upload',
            field=models.ImageField(blank=True, help_text='Primary img', null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='img_upload',
            field=models.ImageField(blank=True, help_text='Primary img', null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Primary file', null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img_upload',
            field=models.ImageField(blank=True, help_text='Primary img', null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img_url',
            field=models.CharField(blank=True, help_text='secondary img', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_url',
            field=models.CharField(help_text='Secondary img', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_url',
            field=models.CharField(blank=True, help_text='secondary img', max_length=300, null=True),
        ),
    ]
