# Generated by Django 3.2.4 on 2021-07-10 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_auto_20210710_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='producttag',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_url',
            field=models.CharField(blank=True, help_text='Secondary img', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ProductTagItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2tagitems', to=settings.AUTH_USER_MODEL)),
                ('product_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag2items', to='product.producttag')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant2tag', to='product.productvariant')),
            ],
        ),
    ]
