# Generated by Django 3.2.4 on 2021-07-10 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_auto_20210710_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTagItems',
            new_name='ProductTagItem',
        ),
    ]
