# Generated by Django 3.2.4 on 2021-07-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shopcart_product_variant'),
        ('product', '0015_auto_20210710_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
