# Generated by Django 3.2.4 on 2021-07-10 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_delete_productvariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant2',
            new_name='ProductVariant',
        ),
    ]
