# Generated by Django 3.2.4 on 2021-08-04 11:47

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_productvariant2_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparent',
            name='img_upload',
            field=models.ImageField(blank=True, help_text='Primary img', null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='productparent',
            name='img_url',
            field=models.CharField(blank=True, help_text='secondary img', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productparent',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
