# Generated by Django 3.2.4 on 2021-08-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210804_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparent',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='sum of variants qty', null=True),
        ),
    ]
