# Generated by Django 3.2.4 on 2021-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productparent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparent',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productparent',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productparent',
            name='totalQty',
            field=models.IntegerField(blank=True, help_text='sum of variants qty', null=True),
        ),
    ]
