# Generated by Django 3.2.4 on 2021-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210804_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productparent',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='productparent',
            name='totalQty',
            field=models.IntegerField(blank=True, help_text='sum of variants qty, if any', null=True),
        ),
    ]
