# Generated by Django 3.2.4 on 2021-08-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210807_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantitem',
            name='name',
        ),
    ]
