# Generated by Django 4.2 on 2023-04-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopprofile'),
        ('product', '0023_remove_productvariantitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparent',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop2product', to='shop.shopprofile'),
        ),
    ]
