# Generated by Django 4.2 on 2023-04-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productparent_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparent',
            name='shop',
        ),
    ]
