# Generated by Django 4.2 on 2023-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_productparent_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantitem',
            name='default',
            field=models.BooleanField(default=False, help_text='default to display in product details page of similar product'),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='price',
            field=models.FloatField(blank=True, help_text='sale price, exclusive of tax', null=True),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='allocated or reserved quantity', null=True),
        ),
    ]
