# Generated by Django 4.2 on 2023-04-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productvariantitem_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productparent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Under Review'), (1, 'Approved'), (2, 'Rejected')], null=True),
        ),
    ]
