# Generated by Django 3.2.4 on 2021-07-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbanner',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='define order sequence'),
            preserve_default=False,
        ),
    ]
