# Generated by Django 4.2 on 2023-05-21 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, help_text='product variant stock keeping unit', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail_url', models.ImageField(blank=True, help_text='thumbnail url', null=True, upload_to=utils.path_and_rename)),
                ('handling_fee', models.DecimalField(blank=True, decimal_places=3, help_text='Add handling fee ', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2warehouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse2stock', to='warehouse.provider'),
        ),
    ]
