# Generated by Django 4.2 on 2023-04-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productvariantitem_default_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant2stock', to='product.productvariant'),
            preserve_default=False,
        ),
    ]
