# Generated by Django 4.2 on 2023-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='status',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
