# Generated by Django 4.2 on 2023-05-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('warehouse', '0002_remove_warehouse_status_warehouse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse2stock', to='provider.provider'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
