# Generated by Django 4.2 on 2023-06-03 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_vendor'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('discount_types', models.TextField(blank=True, help_text="ex. [ {'name': 'Discount by Fix or Percentage', 'by_percentage': 12 }, { 'name': 'Buy N get N', 'buy_qty': 5, 'get_qty': 1 } ]", null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='category2discount', to='product.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2discount', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ManyToManyField(blank=True, related_name='prodvariant2discount', to='product.variantitem')),
                ('shipping_method', models.ManyToManyField(blank=True, related_name='shipmethod2discount', to='shipping.method')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag2discount', to='product.tag')),
                ('vendor', models.ManyToManyField(blank=True, related_name='vendor2discount', to='accounts.vendor')),
            ],
        ),
    ]
