# Generated by Django 4.2 on 2023-05-14 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shipping', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTypeVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('voucher', models.CharField(help_text='Need to enter the voucher to use', max_length=15)),
                ('percent_offer', models.DecimalField(blank=True, decimal_places=3, help_text='N% offer', max_digits=15, null=True)),
                ('fix_offer', models.DecimalField(blank=True, decimal_places=3, help_text='fix amount offer', max_digits=15, null=True)),
                ('min_spend', models.DecimalField(blank=True, decimal_places=3, help_text='min amount spend', max_digits=15, null=True)),
                ('capped_at', models.DecimalField(blank=True, decimal_places=3, help_text='max discount price', max_digits=15, null=True)),
                ('free_shipping', models.BooleanField(default=False, help_text='select for free shipping')),
                ('usage_limit', models.IntegerField(default=1, help_text='limited to number of use')),
                ('img_upload', models.ImageField(blank=True, help_text='Voucher img', null=True, upload_to=utils.path_and_rename)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTypePercentageOrFixAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('minimum_quantity', models.IntegerField(null=True)),
                ('by_percentage', models.DecimalField(blank=True, decimal_places=3, help_text='Discount by percentage', max_digits=15, null=True)),
                ('fix_amount', models.DecimalField(blank=True, decimal_places=3, help_text='Discount by fix amount', max_digits=15, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTypeBuyXGetX',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('buy_quantity', models.IntegerField(null=True)),
                ('get_quantity', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('object_id', models.PositiveIntegerField()),
                ('is_enable', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='category2discount', to='product.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2discount', to=settings.AUTH_USER_MODEL)),
                ('discount_type', models.ForeignKey(help_text='Select a discount rules for shop, tags, or any product variants', limit_choices_to={'app_label': 'discount'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product_variant', models.ManyToManyField(blank=True, related_name='prodvariant2discount', to='product.variantitem')),
                ('shipping_method', models.ManyToManyField(blank=True, related_name='shipmethod2discount', to='shipping.method')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag2discount', to='tag.tag')),
                ('vendor', models.ManyToManyField(blank=True, related_name='vendor2discount', to='vendor.vendor')),
            ],
        ),
    ]
