# Generated by Django 4.2 on 2023-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounttypepercentageorfixamount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discounttypevoucher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='object_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='by_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Discount by percentage', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='fix_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Discount by fix amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.TextField(blank=True, help_text="ex. [ {'name': 'Discount by Fix or Percentage', 'by_percentage': 12 }, { 'name': 'Buy N get N', 'buy_qty': 5, 'get_qty': 1 } ]", null=True),
        ),
        migrations.DeleteModel(
            name='DiscountTypeBuyXGetX',
        ),
        migrations.DeleteModel(
            name='DiscountTypePercentageOrFixAmount',
        ),
        migrations.DeleteModel(
            name='DiscountTypeVoucher',
        ),
    ]
