# Generated by Django 4.2 on 2023-05-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_remove_discounttypepercentageorfixamount_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_type',
            new_name='discount_types',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='by_percentage',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='fix_amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='minimum_quantity',
        ),
    ]
