# Generated by Django 4.2 on 2023-05-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_rename_discount_type_discount_discount_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='vendor',
        ),
    ]
