# Generated by Django 4.2 on 2023-04-17 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0004_alter_discounttypebuyxgetx_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.ForeignKey(help_text='Select a discount rules for shop, tags, or any product variants', limit_choices_to={'app_label': 'discount'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='DiscountTypeVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('voucher', models.CharField(help_text='Need to enter the voucher to use', max_length=15)),
                ('min_spend', models.FloatField(blank=True, help_text='N% min spend', null=True)),
                ('capped_at', models.FloatField(blank=True, help_text='Capped at N%', null=True)),
                ('free_shipping', models.BooleanField(default=False, help_text='select for free shipping')),
                ('use', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
