# Generated by Django 4.2 on 2023-04-17 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0005_alter_discount_discount_type_discounttypevoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTypePercentageOrFixAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('minimum_quantity', models.IntegerField(null=True)),
                ('by_percentage', models.FloatField(blank=True, help_text='Discount by percentage', null=True)),
                ('fix_amount', models.FloatField(blank=True, help_text='Discount by fix amount', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DiscountTypePercentage',
        ),
    ]
