# Generated by Django 4.2 on 2023-04-18 11:38

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_discounttypepercentageorfixamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounttypevoucher',
            name='use',
        ),
        migrations.AddField(
            model_name='discounttypevoucher',
            name='fix_offer',
            field=models.FloatField(blank=True, help_text='fix amount offer', null=True),
        ),
        migrations.AddField(
            model_name='discounttypevoucher',
            name='img_upload',
            field=models.ImageField(blank=True, help_text='Voucher img', null=True, upload_to=utils.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='discounttypevoucher',
            name='percent_offer',
            field=models.FloatField(blank=True, help_text='N% offer', null=True),
        ),
        migrations.AddField(
            model_name='discounttypevoucher',
            name='usage_limit',
            field=models.IntegerField(default=1, help_text='limited to number of use'),
        ),
        migrations.AlterField(
            model_name='discounttypevoucher',
            name='capped_at',
            field=models.FloatField(blank=True, help_text='max discount price', null=True),
        ),
        migrations.AlterField(
            model_name='discounttypevoucher',
            name='min_spend',
            field=models.FloatField(blank=True, help_text='min price spend', null=True),
        ),
    ]
