# Generated by Django 4.2 on 2023-04-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.IntegerField(choices=[(0, 'Create Order'), (1, 'Update Order Status')], null=True)),
                ('secret', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_payload', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2webhook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
