# Generated by Django 5.1.4 on 2024-12-15 12:46

import ddd.product_catalog.domain.enums
import django.db.models.deletion
import utils
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=ddd.product_catalog.domain.enums.CategoryLevel.choices, max_length=15)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor name associated w this product. Leave blank for public availability', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product_catalog.category')),
            ],
            options={
                'unique_together': {('name', 'vendor_name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=ddd.product_catalog.domain.enums.ProductStatus.choices, default=ddd.product_catalog.domain.enums.ProductStatus['DRAFT'], max_length=25, null=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor name associated w this product. Leave blank for public availability', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat2product', to='product_catalog.category')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag2product', to='product_catalog.tag')),
            ],
            options={
                'unique_together': {('name', 'vendor_name')},
            },
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('options', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), help_text='default price, exclusive of tax', max_digits=15, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('img_upload', models.ImageField(blank=True, help_text='Primary img', null=True, upload_to=utils.path_and_rename)),
                ('default', models.BooleanField(default=False, help_text='default to display in product details page of similar product')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product2variantitem', to='product_catalog.product')),
            ],
        ),
    ]
