# Generated by Django 5.1.4 on 2024-12-20 14:29

import ddd.product_catalog.domain.enums
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=ddd.product_catalog.domain.enums.CategoryLevel.choices, max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product_catalog.category')),
                ('vendor', models.ForeignKey(help_text='Vendor name associated w this category', on_delete=django.db.models.deletion.CASCADE, related_name='vendor2category', to='auth.group')),
            ],
            options={
                'unique_together': {('name', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=ddd.product_catalog.domain.enums.ProductStatus.choices, default=ddd.product_catalog.domain.enums.ProductStatus['DRAFT'], max_length=25, null=True)),
                ('attributes', models.JSONField(blank=True, help_text='ex. {"Brand": "X", "Warranty": "1 year"}', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat2product', to='product_catalog.category')),
                ('vendor', models.ForeignKey(help_text='Vendor name associated w this product', on_delete=django.db.models.deletion.CASCADE, related_name='vendor2product', to='auth.group')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag2product', to='product_catalog.tag')),
            ],
            options={
                'unique_together': {('name', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('options', models.JSONField(help_text='ex. {"Size": "M", "Color": "RED"}')),
                ('price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), help_text='default price, exclusive of tax', max_digits=15)),
                ('stock', models.PositiveIntegerField()),
                ('default', models.BooleanField(default=False, help_text='default to display in product details page of similar product')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product2variantitem', to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_upload', models.ImageField(blank=True, help_text='variants img', null=True, upload_to='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant2images', to='product_catalog.variantitem')),
            ],
        ),
    ]
