# Generated by Django 5.1.4 on 2024-12-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('vendor_standard_policy', 'Can use vendor standard policy'), ('vendor_standard_v2_policy', 'Can use vendor standard version2 policy'), ('vendor_standard_v3_policy', 'Can use vendor standard version3 policy')]},
        ),
    ]
