# Generated by Django 5.1.4 on 2024-12-11 13:23

import ddd.domain.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0002_alter_category_level_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(blank=True, choices=ddd.domain.enums.CategoryLevel.choices, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=ddd.domain.enums.ProductStatus.choices, default=ddd.domain.enums.ProductStatus['DRAFT'], max_length=25, null=True),
        ),
    ]
