# Generated by Django 5.1.4 on 2025-01-10 15:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(help_text='e.g WELCOME25', max_length=50)),
                ('start_date', models.DateTimeField(help_text='Only valid on start of this date')),
                ('end_date', models.DateTimeField(help_text='Only valid on before end date')),
                ('is_active', models.BooleanField(default=False, help_text='To control whether this offer is still valid')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='To control whether the is valid')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_cost', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=15)),
                ('conditions', models.JSONField(help_text='ex. only package under 30kg?')),
                ('flat_rate', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=15)),
                ('delivery_time', models.CharField(max_length=255)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='vendor_management.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.CharField(max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), help_text='Percentage or Fix amount?', max_digits=15)),
                ('conditions', models.JSONField(help_text='ex. min_purchase, applicable_products')),
                ('stackable', models.BooleanField(default=False, help_text='Set to True, To combine w other stackable')),
                ('priority', models.PositiveIntegerField(default=0, help_text='The highest number will be prioritized on multistack or single stack')),
                ('required_coupons', models.BooleanField(default=False, help_text='Set to True, To make use of coupons to apply')),
                ('start_date', models.DateTimeField(help_text='Only valid on start of this date; To ignore if required_coupon is True')),
                ('end_date', models.DateTimeField(help_text='Only valid on before end date; To ignore if required_coupon is True')),
                ('manual_apply', models.BooleanField(default=False, help_text='Determine whether to apply manually.; To ignore if required_coupons')),
                ('is_active', models.BooleanField(default=False, help_text='To control whether this offer is still valid')),
                ('coupon', models.ManyToManyField(to='vendor_management.coupon')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vendor_management.vendor')),
            ],
        ),
    ]
