# Generated by Django 5.1.4 on 2025-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='coupon',
            field=models.ManyToManyField(blank=True, help_text='Provide a coupons to manually apply for this offer.', to='vendor_management.coupon'),
        ),
    ]
