# Generated by Django 5.1.4 on 2025-01-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='conditions',
            field=models.CharField(help_text='ex. min_purchase, applicable_products', max_length=150),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='conditions',
            field=models.CharField(help_text='ex. only package under 30kg?', max_length=150),
        ),
    ]
