# Generated by Django 5.1.4 on 2025-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingoption',
            name='currency',
            field=models.CharField(default='SGD', help_text='Default currency specific to this Shipping option base cost or flat rate', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='conditions',
            field=models.CharField(help_text='ex. { "max_weight": 30 }', max_length=150),
        ),
    ]
