# Generated by Django 5.1.4 on 2025-02-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_alter_offer_conditions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='required_coupons',
            new_name='required_coupon',
        ),
    ]
