# Generated by Django 5.1.4 on 2025-09-06 16:14

import ddd.order_management.domain.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, max_length=25, null=True)),
                ('step', models.CharField(help_text='should match w command handler name, e.g. PendingApprovalCommand', max_length=50)),
                ('sequence', models.PositiveIntegerField(help_text='sequence of steps')),
                ('performed_by', models.CharField(help_text='system or user or reviewer or other', max_length=50)),
                ('user_input', models.CharField(help_text='{"comment": "Looks good"}', max_length=500)),
                ('optional_step', models.BooleanField(default=False, help_text='can skip')),
                ('step_status', models.CharField(blank=True, choices=ddd.order_management.domain.enums.StepStatus.choices, max_length=25, null=True)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_activities', to='order_management.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderWorkflowActivities',
        ),
    ]
