# Generated by Django 5.2.6 on 2025-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactivities',
            name='conditions',
            field=models.CharField(blank=True, help_text='optional condition ex. {"non_refundable": false }', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenantworkflowsnapshot',
            name='conditions',
            field=models.CharField(blank=True, help_text='optional condition ex. {"non_refundable": false }', max_length=150, null=True),
        ),
    ]
