# Generated by Django 5.1.4 on 2025-06-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcouponsnapshot',
            old_name='coupon_id',
            new_name='vendor_id',
        ),
    ]
