# Generated by Django 5.1.4 on 2025-07-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthorizationsnapshot',
            name='tenant_id',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauthorizationsnapshot',
            name='scope',
            field=models.CharField(help_text='ex. { "customer_id": "c-1234" }', max_length=150),
        ),
    ]
