# Generated by Django 5.2.6 on 2025-11-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='package_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value should be coming from product itself or to fill in later once it goes to warehouse fulfillment?', max_digits=15, null=True),
        ),
    ]
