# Generated by Django 5.1.4 on 2025-01-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='delivery_street',
        ),
    ]
