# Generated by Django 5.1.4 on 2025-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproductsnapshot',
            name='is_free_gift',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vendorproductsnapshot',
            name='is_taxable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
