# Generated by Django 5.1.4 on 2025-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorshippingoptionsnapshot',
            name='provider',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
