# Generated by Django 5.1.4 on 2025-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_rename_coupon_id_vendorcouponsnapshot_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcouponsnapshot',
            old_name='vendor_id',
            new_name='offer_id',
        ),
        migrations.RemoveField(
            model_name='vendoroffersnapshot',
            name='coupon',
        ),
        migrations.AddField(
            model_name='vendoroffersnapshot',
            name='offer_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
