# Generated by Django 5.1.4 on 2025-06-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_vendorcouponsnapshot_vendordetailssnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductSnapshot',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, serialize=False)),
                ('vendor_id', models.UUIDField()),
                ('product_sku', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(help_text='some countries uses category to calculate tax', max_length=100)),
                ('options', models.CharField(help_text='ex. {"Size": "M", "Color": "RED"}', max_length=150)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('product_currency', models.CharField(help_text='Currency for calculation requirements & validation. e.g. SGD', max_length=50)),
                ('package_weight', models.CharField(blank=True, help_text='value should be coming from product itself or to fill in later once it goes to warehouse fulfillment?', max_length=100, null=True)),
                ('package_length', models.CharField(blank=True, help_text='value should be coming from product itself or to fill in later once it goes to warehouse fulfillment? ', max_length=100, null=True)),
                ('package_width', models.CharField(blank=True, help_text='value should be coming from product itself or to fill in later once it goes to warehouse fulfillment?', max_length=100, null=True)),
                ('package_height', models.CharField(blank=True, help_text='value should be coming from product itself or to fill in later once it goes to warehouse fulfillment?', max_length=100, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('product_sku', 'vendor_id')},
            },
        ),
    ]
