# Generated by Django 5.1.4 on 2025-08-23 08:02

import ddd.order_management.domain.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_vendorshippingoptionsnapshot_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaymentOptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=150)),
                ('tenant_id', models.CharField(max_length=150)),
                ('method', models.CharField(blank=True, choices=ddd.order_management.domain.enums.PaymentMethod.choices, max_length=50, null=True)),
                ('provider', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False, help_text='To quickly control whether this option is still valid')),
                ('last_update_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vendorproductsnapshot',
            unique_together={('product_sku', 'tenant_id', 'vendor_id')},
        ),
    ]
