# Generated by Django 5.1.4 on 2025-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_rename_delivery_address_order_delivery_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_coupons',
            field=models.CharField(blank=True, help_text='e.g. ["WELCOME25", "FREESHIP"]', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_details',
            field=models.CharField(blank=True, help_text='e.g. ["Free Shipping applied", "Discount applied: $20.00"]', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_details',
            field=models.CharField(blank=True, help_text='e.g. ["GST (9%)", "Local State (2%)"]', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='options',
            field=models.CharField(help_text='ex. {"Size": "M", "Color": "RED"}', max_length=150),
        ),
    ]
