# Generated by Django 5.1.4 on 2025-06-21 06:48

import ddd.order_management.domain.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_orderline_id_alter_orderline_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=ddd.order_management.domain.enums.PaymentStatus.choices, max_length=50, null=True),
        ),
    ]
