# Generated by Django 5.2.6 on 2025-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_lineitem_package_weight_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_tax_amount',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='allocated_shipping_tax',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='allocated_shipping_tax_currency',
        ),
    ]
