# Generated by Django 5.2.6 on 2025-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_remove_shipment_shipment_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
