# Generated by Django 5.1.4 on 2025-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_rename_vendor_id_vendorcouponsnapshot_offer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetailssnapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='customeraddresssnapshot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerdetailssnapshot',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerdetailssnapshot',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetailssnapshot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerdetailssnapshot',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetailssnapshot',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorproductsnapshot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorproductsnapshot',
            name='last_update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserAuthorizationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('permission_codename', models.CharField(max_length=255)),
                ('scope', models.CharField(help_text='ex. { "vendor_id": "v-1234" }', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_id', 'permission_codename', 'scope')},
            },
        ),
    ]
