# Generated by Django 5.1.4 on 2025-08-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_vendorpaymentoptionsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpaymentoptionsnapshot',
            name='conditions',
            field=models.CharField(default=None, help_text='ex. { "country": "US" }', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorpaymentoptionsnapshot',
            name='option_name',
            field=models.CharField(default=None, help_text='Just a name of this payment Option. e.g. Credit Card (Stripe) ', max_length=255),
            preserve_default=False,
        ),
    ]
