# Generated by Django 5.1.4 on 2025-06-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_order_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAuthorizationSnapshot',
            new_name='UserAuthorization',
        ),
    ]
