# Generated by Django 5.1.4 on 2025-06-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_order_customer_id_alter_order_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddresssnapshot',
            old_name='postal_code',
            new_name='postal',
        ),
    ]
