# Generated by Django 4.2 on 2023-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product_variant',
            field=models.ManyToManyField(blank=True, related_name='prodvariant2tag', to='product.variantitem'),
        ),
        migrations.DeleteModel(
            name='TagItem',
        ),
    ]
