@startuml Two Modes - Technical View
' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v20.0/dist
!include AWSPuml/AWSCommon.puml

' Uncomment the following line to create simplified view
' !include AWSPuml/AWSSimplified.puml

!include AWSPuml/General/Users.puml
!include AWSPuml/NetworkingContentDelivery/APIGateway.puml
!include AWSPuml/SecurityIdentityCompliance/Cognito.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/ApplicationIntegration/EventBridge.puml


left to right direction

Users(sources, "User/Webhook Request", "millions of users/webhooks")
APIGateway(tenantOMSApi, "Tenant OMS API", "receive graphql request or webhook request")
' Cognito(userAuth, "User Authentication", "jwt to submit order")
' Lambda(generateToken, "User Credentials", "return jwt")
SimpleStorageService(DDD, "DDD", "Attach DDD python code to lambda's / Lambda layers to serve Python Non standard lib")
Lambda(graphqlRequest, "Graphql Adapter", "delegate the graphql request handling to DDD w built-in internal message bus, handlers, etc.")
Lambda(webhookRequest, "Webhook Adapter", "delegate the webhook request handling to DDD w built-in internal message bus, handlers, etc.")
Lambda(eventHandler, "Event Handler Adapter", "delegate the webhook request handling to DDD w built-in internal event bus, etc.")
DynamoDB(orderDb, "Order Database", "single order table")
EventBridge(event, "Event Bus", "default event bus")

' sources --> userAuth
sources --> tenantOMSApi
' userAuth <--> generateToken

DDD --> graphqlRequest
DDD --> webhookRequest
DDD --> eventHandler
tenantOMSApi <--> graphqlRequest
graphqlRequest <--> orderDb
graphqlRequest --> event
tenantOMSApi <--> webhookRequest
webhookRequest --> event
webhookRequest <--> orderDb
event --> eventHandler
@enduml
