# Generated by Django 4.2 on 2023-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='status',
        ),
        migrations.AddField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
