# Generated by Django 4.2 on 2023-04-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.FloatField(blank=True, help_text='N% tax rate per order?', null=True, verbose_name='Rate(%)'),
        ),
    ]
