# Generated by Django 4.2 on 2023-05-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='region',
        ),
        migrations.AddField(
            model_name='tax',
            name='rates',
            field=models.TextField(blank=True, help_text="ex. [{ 'name': 'Standard Rate', 'country': 'SGP', 'percentage':  8 } ]", null=True),
        ),
    ]
