# Generated by Django 2.2.17 on 2021-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210616_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Waiting for Payment'), (1, 'Paid'), (2, 'Processing'), (3, 'Shipped Out'), (4, 'Refunded'), (5, 'Cancel'), (6, 'Completed')], null=True),
        ),
    ]
