# Generated by Django 3.2.4 on 2021-07-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210616_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Waiting For Payment'), (1, 'Paid'), (2, 'Processing'), (3, 'Shipped Out'), (4, 'Refunded'), (5, 'Cancel'), (6, 'Completed')], null=True),
        ),
    ]
