# Generated by Django 4.2 on 2023-04-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_productparent_shop'),
        ('shop', '0008_shopprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='product',
            field=models.ManyToManyField(to='product.productparent'),
        ),
    ]
