# Generated by Django 4.2 on 2023-04-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotional', '0002_promotionalbanner_display_order'),
        ('product', '0025_remove_productparent_shop'),
        ('shop', '0010_shopprofile_category_shopprofile_promotional_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='category',
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='prod2shop', to='product.productparent'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='promotional_banner',
            field=models.ManyToManyField(blank=True, related_name='banner2shop', to='promotional.promotionalbanner'),
        ),
    ]
