# Generated by Django 4.2 on 2023-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_discount_tag_img_upload_tag_img_url'),
        ('discount', '0002_remove_discount_discount_percentage_and_more'),
        ('shop', '0011_remove_shopprofile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='promotional_banner',
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='discount',
            field=models.ManyToManyField(blank=True, related_name='discount2shop', to='discount.discount'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag2shop', to='tag.tag'),
        ),
    ]
