# Generated by Django 4.2 on 2023-04-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_shopprofile_promotional_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='tag',
        ),
    ]
