# Generated by Django 4.2 on 2023-04-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='country',
            field=models.CharField(blank=True, help_text='Singapore, .. ?', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='multi_vendor',
            field=models.BooleanField(default=1, help_text='allow external sellers'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(blank=True, help_text='USD, SGD, ..', max_length=10, null=True),
        ),
    ]
