from __future__ import annotations
import hmac, hashlib
from typing import Tuple, Protocol, Mapping

class WebhookReceiverAbstract(Protocol):
    #def verify(self, headers, body) -> bool: ...
    def verify(self, headers: Mapping[str, str], raw_body: bytes, request_path: str) -> bool: ...
    #def generate_signature(self, secret: str, body: bytes) -> str: ...