from __future__ import annotations
from typing import Protocol, Any

class LoggingAbstract(Protocol):
    def log(self, message: str, **kwargs: Any) -> None: ...
    #def warning(self, message: str, **kwargs: Any) -> None: ...
    #def error(self, message: str, **kwargs: Any) -> None: ...
    #def debug(self, message: str, **kwargs: Any) -> None: ...