# Generated by Django 4.2 on 2023-04-19 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0002_remove_tag_discount_tag_img_upload_tag_img_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ex. Zone 1', max_length=50)),
                ('country', models.CharField(help_text='ex. Singapore', max_length=50)),
                ('region', models.CharField(help_text='ex. Tampines', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2zone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='ex. Free shipping, Local pickup', max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('cost', models.FloatField(blank=True, help_text='cost or overall cost?', null=True)),
                ('enable', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2method', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(blank=True, related_name='tag2method', to='tag.tag')),
                ('zone', models.ManyToManyField(blank=True, related_name='zone2method', to='shipping.zone')),
            ],
        ),
    ]
