# Generated by Django 4.2 on 2023-06-03 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('accounts', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('tracker_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, help_text='company logo', null=True, upload_to=utils.path_and_rename)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ex. Zone 1', max_length=50)),
                ('country', models.CharField(help_text='ex. Singapore', max_length=50)),
                ('region', models.CharField(help_text='ex. Tampines', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2zone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ex. Free shipping, Local pickup', max_length=50)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('rates', models.TextField(blank=True, help_text="ex. [{ 'name': '3 hours express', 'max_Weight_kg': 1, min_LWH_cm: 60, 'cost':  14 }, { 'name': 'Specific Delivery Slot', 'max_Weight_kg': 1, min_LWH_cm: 60, 'cost':  18 }, ]", null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier2method', to='shipping.carrier')),
                ('category', models.ManyToManyField(blank=True, related_name='category2method', to='product.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2method', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ManyToManyField(blank=True, related_name='prodvariant2method', to='product.variantitem')),
                ('shipping_zone', models.ManyToManyField(blank=True, related_name='zone2method', to='shipping.zone')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag2method', to='product.tag')),
                ('vendor', models.ManyToManyField(blank=True, related_name='vendor2method', to='accounts.vendor')),
            ],
        ),
    ]
