# Generated by Django 4.2 on 2023-04-29 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='method',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='shipping_method',
            field=models.ManyToManyField(blank=True, related_name='shipmethod2zone', to='shipping.method'),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex. Heavy Weight', max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('min_weight', models.FloatField(blank=True, help_text='minimum weight of the individual item or all ordered items??', null=True)),
                ('max_weight', models.FloatField(blank=True, help_text='max weight of the individual item or all ordered items??', null=True)),
                ('min_dimension', models.FloatField(blank=True, help_text='min package dimension', null=True)),
                ('max_dimension', models.FloatField(blank=True, help_text='max package dimension, should per ordered items??', null=True)),
                ('cost', models.FloatField(blank=True, help_text='the cost if condition matched', null=True)),
                ('class_type', models.IntegerField(choices=[(0, 'Entire Order'), (1, 'Per Item')], help_text='apply per order or per item?', null=True)),
                ('priority', models.IntegerField(blank=True, help_text='multiple classification need to have a priority', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2classification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='classification',
            field=models.ManyToManyField(blank=True, related_name='class2shipmethod', to='shipping.classification'),
        ),
    ]
