# Generated by Django 4.2 on 2023-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='note',
        ),
        migrations.AddField(
            model_name='method',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='min_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
