# Generated by Django 4.2 on 2023-04-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_rename_title_method_name_remove_method_zone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='enable',
            new_name='is_enable',
        ),
    ]
