# Generated by Django 4.2 on 2023-05-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_remove_fulfillment_status_fulfillment_is_active'),
        ('shipping', '0003_rename_enable_method_is_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='desc',
        ),
        migrations.AddField(
            model_name='method',
            name='note',
            field=models.CharField(blank=True, help_text='ex. 2-5 days delivery', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment2method', to='fulfillment.fulfillment'),
        ),
    ]
