# Generated by Django 4.2 on 2023-05-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_packaging_remove_method_cost_remove_method_max_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='classification',
            new_name='rates',
        ),
    ]
