# Generated by Django 4.2 on 2023-05-21 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0004_rename_classification_method_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company_url', models.CharField(blank=True, max_length=200, null=True)),
                ('tracker_url', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_url', models.CharField(blank=True, help_text='thumbnail url', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2carrier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='method',
            name='category',
        ),
        migrations.RemoveField(
            model_name='method',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='method',
            name='shipping_zone',
        ),
        migrations.RemoveField(
            model_name='method',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='method',
            name='vendor',
        ),
        migrations.AddField(
            model_name='zone',
            name='shipping_method',
            field=models.ManyToManyField(blank=True, related_name='method2zone', to='shipping.method'),
        ),
        migrations.DeleteModel(
            name='Packaging',
        ),
        migrations.AlterField(
            model_name='method',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider2method', to='shipping.provider'),
        ),
    ]
