# Generated by Django 4.2 on 2023-05-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0005_provider_remove_method_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('discount_types', models.TextField(blank=True, help_text="ex. [ {'name': 'Discount by Fix or Percentage', 'by_percentage': 12 }, { 'name': 'Free shipping', 'cost': 0 } ]", null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2shipdiscount', to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ManyToManyField(blank=True, related_name='shipmethod2discount', to='shipping.method')),
            ],
        ),
    ]
