# Generated by Django 2.2 on 2019-04-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('status', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('encrypted_sku', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('size', models.CharField(max_length=5, null=True)),
                ('ship_weight', models.FloatField(null=True)),
                ('volume_weight', models.FloatField(null=True)),
                ('cat_id', models.IntegerField(null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('goods_brand', models.CharField(max_length=30, null=True)),
                ('purchase_title', models.CharField(max_length=100, null=True)),
                ('package_length', models.FloatField(null=True)),
                ('package_width', models.FloatField(null=True)),
                ('package_height', models.FloatField(null=True)),
                ('size_chart', models.CharField(max_length=100, null=True)),
                ('convert_size_chart', models.CharField(max_length=100, null=True)),
                ('packing_expense', models.FloatField(null=True)),
                ('map', models.TextField(null=True)),
                ('forbid_platform', models.CharField(max_length=25, null=True)),
                ('permit_platform', models.CharField(max_length=25, null=True)),
                ('forbid_region', models.CharField(max_length=25, null=True)),
                ('permit_region', models.CharField(max_length=25, null=True)),
                ('goods_nature', models.CharField(max_length=5, null=True)),
                ('shipping_attributes', models.CharField(max_length=25, null=True)),
                ('original_img', models.TextField(null=True)),
                ('desc_img', models.TextField(null=True)),
                ('goods_desc', models.TextField(null=True)),
                ('last_update', models.DateField(null=True)),
                ('is_amazon_select', models.IntegerField(null=True)),
                ('warehouse_list', models.TextField(null=True)),
            ],
        ),
    ]
