# Generated by Django 2.2 on 2019-05-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.CharField(choices=[('YB', 'CN-1'), ('FXQHBSWH', 'CN-2'), ('FCYWHQ', 'CN-8'), ('FXLAWH', 'US-1'), ('FXLAWH2', 'US-2'), ('MXTJWH', 'US-3'), ('FXJFKGC', 'US-4'), ('GBYKDFX', 'UK-3'), ('UKCBWH', 'UK-1'), ('FXRUWJ', 'RU-2'), ('FREDCGC', 'FR-1'), ('AU4PXHXY', 'AU-1'), ('ESTJWH', 'ES-1'), ('FXHKGCZY', 'HK-4'), ('ZQ01', 'CN-5'), ('ZQDZ01', 'CN-7')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(null=True)),
                ('goods_number', models.PositiveIntegerField(null=True)),
                ('goods_state', models.CharField(max_length=50, null=True)),
                ('goods_sn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod2stock', to='cb.Product')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse2stock', to='cb.ProductWarehouse')),
            ],
        ),
    ]
