# Generated by Django 4.2 on 2023-06-03 12:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnails_upload', models.ImageField(blank=True, help_text='primary thumbnails', null=True, upload_to=utils.path_and_rename)),
                ('handling_fee', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), help_text='Add handling fee ', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2warehouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, help_text='warehouse stocks ', null=True)),
                ('low_stock', models.IntegerField(blank=True, help_text='warehouse low stock to track inventory? ', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), help_text='warehouse stock price', max_digits=15, null=True)),
                ('status', models.IntegerField(choices=[(0, 'In Stock'), (1, 'Out Of Stock'), (2, 'Low Stock')], null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2stock', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodvariant2stock', to='product.variantitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse2stock', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, help_text='product  weight', null=True)),
                ('package_length', models.FloatField(blank=True, help_text='package weight', null=True)),
                ('package_width', models.FloatField(blank=True, help_text='package width', null=True)),
                ('package_height', models.FloatField(blank=True, help_text='package height', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2packaging', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodvariant2packaging', to='product.variantitem')),
            ],
        ),
    ]
