# Generated by Django 4.2 on 2023-04-24 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('accounts', '0001_initial'),
        ('tax', '0001_initial'),
        ('payment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_fee', models.FloatField(blank=True, help_text='locked-in shipping fee', null=True)),
                ('discount_fee', models.FloatField(blank=True, help_text='locked-in discount fee', null=True)),
                ('tax_rate', models.FloatField(blank=True, help_text='locked-in tax rate', null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Customer notes to seller')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Waiting For Payment'), (1, 'Paid'), (2, 'Processing'), (3, 'Shipped Out'), (4, 'Refunded'), (5, 'Cancel'), (6, 'Completed')], null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user2order', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_payment2order', to='payment.paymentmethod')),
                ('shipping_address', models.ForeignKey(blank=True, help_text='delivery address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address2order', to='accounts.address')),
                ('tax', models.ForeignKey(blank=True, help_text='Country tax applied', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax2order', to='tax.tax')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(null=True)),
                ('locked_in_price', models.FloatField(blank=True, help_text='Locked-In Price, This wont use the new product price once item is ordered', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user2orderitem', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_order2orderitem', to='order.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_prodvariant2cart', to='product.productvariantitem')),
            ],
        ),
    ]
