# Generated by Django 4.2 on 2023-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, related_name='discount2order', to='discount.discount'),
        ),
    ]
