# Generated by Django 4.2 on 2023-04-29 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, help_text='a string fulfillment tracking number', max_length=120, null=True)),
                ('name', models.CharField(max_length=20)),
                ('company_url', models.CharField(blank=True, max_length=200, null=True)),
                ('tracker_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, help_text='company logo', null=True, upload_to=utils.path_and_rename)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2orderfulfillment', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfill2orderfulfill', to='fulfillment.fulfillment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order2orderfulfill', to='order.order')),
            ],
        ),
    ]
