# Generated by Django 4.2 on 2023-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_in_price',
            field=models.FloatField(blank=True, help_text='Locked-In Price, This wont use the new product price once item is ordered', null=True),
        ),
    ]
