# Generated by Django 4.2 on 2023-04-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_tax_rate'),
        ('accounts', '0003_remove_address_userprofile_address_user_and_more'),
        ('product', '0027_productvariantitem_status_alter_productparent_status'),
        ('order', '0002_alter_orderitem_locked_in_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_fee',
            field=models.FloatField(blank=True, help_text='locked-in discount fee', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, help_text='Customer notes to seller', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='delivery address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address2order', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(blank=True, help_text='locked-in shipping fee', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Country tax applied', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax2order', to='tax.tax'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.FloatField(blank=True, help_text='locked-in tax rate', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_prodvariant2cart', to='product.productvariantitem'),
        ),
    ]
