# Generated by Django 4.2 on 2023-05-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_tracking_number_orderfulfillment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_desc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_title',
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_cost',
            field=models.FloatField(blank=True, help_text='cost or overall cost?', null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_country',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_method_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_postal',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_region',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_title',
            field=models.CharField(blank=True, help_text='ex. Free shipping, Local pickup', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Fulfilled'), (1, 'Fulfilled'), (2, 'Cancel')], null=True),
        ),
    ]
