# Generated by Django 4.2 on 2023-04-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_customer_address_order_discount_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Customer notes to seller'),
            preserve_default=False,
        ),
    ]
