# Generated by Django 4.2 on 2023-05-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_rename_enable_method_is_enable'),
        ('order', '0003_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfulfillment',
            name='shipping_method_id',
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Not applicable if all items has the same fulfillment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem2orderfulfill', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipmethod2orderfulfillment', to='shipping.method'),
        ),
    ]
