# Generated by Django 4.2 on 2023-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderfulfillment_shipping_method_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfulfillment',
            old_name='name',
            new_name='provider_name',
        ),
        migrations.RenameField(
            model_name='orderfulfillment',
            old_name='shipping_cost',
            new_name='shipping_mehotd_cost',
        ),
        migrations.RenameField(
            model_name='orderfulfillment',
            old_name='shipping_title',
            new_name='shipping_method_name',
        ),
        migrations.RemoveField(
            model_name='orderfulfillment',
            name='fulfillment',
        ),
        migrations.RemoveField(
            model_name='orderfulfillment',
            name='shipping_desc',
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='fulfillment_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='shipping_method_note',
            field=models.CharField(blank=True, help_text='ex. 2-3 days delivery', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Waiting For Payment'), (1, 'Paid'), (2, 'Processing'), (3, 'Partially Shipped Out'), (4, 'Shipped Out'), (5, 'Refunded'), (6, 'Cancel'), (7, 'Completed')], null=True),
        ),
    ]
