# Generated by Django 4.2 on 2023-05-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_alter_method_provider'),
        ('order', '0005_rename_name_orderfulfillment_provider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfulfillment',
            name='fulfillment_id',
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='provider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='provider_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipmethod2fulfillment', to='shipping.method'),
        ),
    ]
